apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mrpe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mrpe
    app.kubernetes.io/part-of: test-app
  name: devfile-sample-mrpe
  namespace: rh-ee-jsmid-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-mrpe
    weight: null
status: {}
